version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '3001:3000'
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - PORT=3000

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - PORT=3000

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdatabase
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
